### ISSUE TITLE
Allow setting redirect code (Feature Request)

### ISSUE THREAD

**Issue by micmath** [hviana/faster#8]
The `redirect` method is [hardcoded to use the `301`](https://github.com/hviana/faster/blob/dbf3d74890d64b1570c2f6d5e9744d1dc8ae58de/server.ts#L67) response code. The `301` code indicates that the resource has **permanently moved** to a new location. There are some scenarios where a redirect is needed but the response code should not be `301`.

For example when an application follows [the "post/redirect/get" pattern](https://en.wikipedia.org/wiki/Post/Redirect/Get) of handling a form submission, where the data is posted to one URL, then processed, and then the browser is redirected to GET another URL, a "thank you" type of page for example. In that case a `301` redirect is inappropriate since it will get cached (and reasonably so, since we said the resource was "permanently" moved) and the next time the same form is submitted the browser never sends any data it just immediately displays the cached result of the redirect instead.

The solution would be to allow the developer to optionally specify _the type_ of redirect they want, for example `302` for temporary redirects, or `303` for other.

**Comment by micmath** [comment]
Note: This would be similar to the [ExpressJS API for redirects](https://expressjs.com/en/api.html#res.redirect): `res.redirect([status,] path)`

**Comment by hviana** [comment]
Implemented, exactly the same as the ExpressJS API.

**Comment by hviana** [comment]
Please like the repository.

**Comment by micmath** [comment]
I LOVE the repository! Thanks for your quick response, sir.

**Comment by micmath** [comment]
I tooted. https://fosstodon.org/@micmath/113176673885683516
